
CREATE DATABASE mesacademydb;

CREATE USER 'mesacademy'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON mesacademydb.* TO 'mesacademy'@'localhost';
FLUSH PRIVILEGES;

USE mesacademydb;

-- MySQL Script generated by MySQL Workbench
-- Mon Jul 29 11:48:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mesacademydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mesacademydb` ;

-- -----------------------------------------------------
-- Schema mesacademydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mesacademydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mesacademydb` ;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Image` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NULL,
  `path` VARCHAR(125) NOT NULL,
  `type` VARCHAR(10) NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `create user` VARCHAR(45) NULL,
  `update_time` DATETIME  ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NULL,
  `lastname` VARCHAR(75) NULL,
  `mail` VARCHAR(125) NULL,
  `username` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `sex` VARCHAR(2) NULL,
  `phone` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `idImage` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `idImage_idx` (`idImage` ASC) VISIBLE,
  CONSTRAINT `idImage`
    FOREIGN KEY (`idImage`)
    REFERENCES `mesacademydb`.`TBL_Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Course` (
  `idCourse` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(125) NOT NULL,
  `description` VARCHAR(10000) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `idImage` INT NULL,
  `idAuthor` INT NULL,
  `suscription` VARCHAR(3) NULL COMMENT 'need suscription\nNO = No necesita suscripcion\nYES = si necesita suscripcion',
  PRIMARY KEY (`idCourse`),
  INDEX `idImagen_idx` (`idImage` ASC) VISIBLE,
  INDEX `idAuthor_idx` (`idAuthor` ASC) VISIBLE,
  CONSTRAINT `idImage`
    FOREIGN KEY (`idImage`)
    REFERENCES `mesacademydb`.`TBL_Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAuthor`
    FOREIGN KEY (`idAuthor`)
    REFERENCES `mesacademydb`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_CourseContent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_CourseContent` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_CourseContent` (
  `idCourseContent` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(125) NULL,
  `description` VARCHAR(2500) NULL,
  `videoLocation` VARCHAR(500) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `idCourse` INT NULL,
  PRIMARY KEY (`idCourseContent`),
  INDEX `idCourse_idx` (`idCourse` ASC) VISIBLE,
  CONSTRAINT `idCourse`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mesacademydb`.`TBL_Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Plan` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Plan` (
  `idPlan` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(125) NULL,
  `description` VARCHAR(1500) NULL,
  `cost` DOUBLE(16,2) NULL,
  `months` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_user` TIMESTAMP NULL,
  `update_user` VARCHAR(45) NULL DEFAULT 'ON UPDATE CURRENT_TIMESTAMP',
  `status` VARCHAR(2) NULL DEFAULT 'A',
  PRIMARY KEY (`idPlan`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Suscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Suscription` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Suscription` (
  `idSuscription` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `idPlan` INT NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`idSuscription`),
  INDEX `idPlan_idx` (`idPlan` ASC) VISIBLE,
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idPlan`
    FOREIGN KEY (`idPlan`)
    REFERENCES `mesacademydb`.`TBL_Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mesacademydb`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_CourseProgress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_CourseProgress` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_CourseProgress` (
  `idCourseProgress` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(6) NULL,
  `status` VARCHAR(2) NULL DEFAULT 'I' COMMENT 'Estado de video visualizado C = Completado, I = en Curso',
  `idCourseContent` INT NULL,
  `idUser` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourseProgress`),
  INDEX `idCourseContent_idx` (`idCourseContent` ASC) VISIBLE,
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idCourseContent`
    FOREIGN KEY (`idCourseContent`)
    REFERENCES `mesacademydb`.`TBL_CourseContent` (`idCourseContent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `mesacademydb`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Promotion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Promotion` (
  `idPromotion` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `title` VARCHAR(75) NULL,
  `discount` INT NULL,
  `ON UPDATE CURRENT_TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL,
  `update_user` VARCHAR(45) NULL DEFAULT 'ON UPDATE CURRENT_TIMESTAMP',
  PRIMARY KEY (`idPromotion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_PlanPromition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_PlanPromition` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_PlanPromition` (
  `idPlanPromition` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(2) NULL,
  `start_day` TIMESTAMP NULL,
  `active_days` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `idPromotion` INT NULL,
  `idPlan` INT NULL,
  PRIMARY KEY (`idPlanPromition`),
  INDEX `idPlan_idx` (`idPlan` ASC) VISIBLE,
  INDEX `idPromotion_idx` (`idPromotion` ASC) VISIBLE,
  CONSTRAINT `idPlan`
    FOREIGN KEY (`idPlan`)
    REFERENCES `mesacademydb`.`TBL_Plan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPromotion`
    FOREIGN KEY (`idPromotion`)
    REFERENCES `mesacademydb`.`TBL_Promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Payment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `amount` DOUBLE(16,2) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `update_user` VARCHAR(45) NULL,
  `id_user` INT NULL,
  `reference` VARCHAR(125) NULL,
  `app` VARCHAR(45) NULL,
  `TBL_Paymentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `idUser_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`id_user`)
    REFERENCES `mesacademydb`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mesacademydb`.`TBL_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesacademydb`.`TBL_Role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mesacademydb`.`TBL_Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `create_time` TIMESTAMP NULL,
  `create_user` VARCHAR(45) NULL,
  `update_time` TIMESTAMP NULL,
  `update_user` VARCHAR(45) NULL,
  `code` VARCHAR(20) NOT NULL COMMENT 'Codigos \n\n10001 - Administrador\n10002 - Estudiante\n10003 - Administrador de cursos',
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
